### PR TITLE
Add OpenSea Base Mint Ingestor

### PR DESCRIPTION
**Pull request by polymawutor**
A PR to add an OpenSea Base Mint Ingestor to the Mobile Minting platform. For Issue #7 

How to get the contract address of a Drop (mint collection) on OpenSea:

Example minting page URL: https://opensea.io/collection/parallel-ocs-24-starter-bundle/overview 

First, make sure that the Drop is hosted on the Base chain. This is shown on the minting page.

On the minting page, right next to the name, click on the '_more_' (three dots) icon. 

Among the options, select '_View on Basescan_' which will open a new window on Basecan with the contract address. 

Please for your perusal @christinehall

### CODE REVIEW

**Comment by chrismaddern** [comment]
Hi 👋 

Excited to see this come in 🥳 

It looks like the URL → Contract functionality isn't viable here. That's okay (I think @christinehall mentioned you chatted) but in that case, can we:

* Return `false` for all `supportsUrl` calls — this ingestor does not support ingesting by URL
* Remove any logic for that callpath (I got a little confused reading it since it then passes a hardcoded contract to the ingest via contract method, which seems wrong?)
* Sync the main mobile minting repo to your fork, and merge main → your branch. 
* Use `setCreator` on the builder to set the creator properties e.g. here https://github.com/floornfts/mobile-minting/blob/main/src/ingestors/fxhash/index.ts#L51

Cheers!

**Comment by mawutory** [comment]
How is it looking now? I could only add `name`, and `websiteUrl`  for `setCreator` properties to the builder.

**Comment by chrismaddern** [comment]
Thank you for the update!! 🥳 🙏 

We've gotten a little behind on reviewing these, but will be spending some time over the next 48 hours, so look out for some feedback soon! Thank you! 🙏

**Comment by mawutory** [comment]
thank you. please can i make more submissions while you're at it?

**Comment by chrismaddern** [comment]
Hi 👋 

I just tried a basic ingestion locally and it doesn't appear to work for me?

CleanShot 2024-07-16 at 14 45 01@2x

using 

```
yarn run dry-run opensea contract 8453:0x0852af8836a0fbf8dc7a3556b3dd46109d29d0fb
```

Can you make sure that it works (or let me know what I'm doing wrong)

Ingestion via URL -- I do believe this data is available via API and would like to see both URL & contract support ideally

**Comment by mawutory** [comment]
yes you're right. i was taking the `creatorName` and `creatorWebsite` from the `external_url` property returned from calling `baseURI` which is an IPFS URL. 

i thought it was smart, but the mint you tried to ingest did not provide `external_url` hence the error.

please allow me some time to get the data via API (https://docs.opensea.io/reference/api-overview) and update the PR accordingly.

**Comment by mawutory** [comment]
hi @chrismaddern 

please i have updated the PR to enable mint ingestion via both URL and contract and all tests passed.

the only caveat here is that you'll need to define `OPENSEA_API_KEY` in `.env`.

you can obtain an API key using this guide: https://docs.opensea.io/reference/api-keys

thanks!

**Comment by chrismaddern** [comment]
Hi @mawutory 👋 

I added an Opensea API Key, and ran the tests, merged with the latest state of main

```
  opensea
    ✔ createMintTemplateForUrl: Returns a mint template for a supported URL (692ms)
    ✔ createMintTemplateForContract: Returns a mint template for a supported contract (384ms)
    OpenSeaIngestor-auto
      ✔ supportsUrl: Returns true for a supported URL (132ms)
      ✔ supportsUrl: Returns false for unsupported url (https://opensea.io/collection/)
      ✔ supportsUrl: Returns false for unsupported url (https://notopensea.io/collection/parallel-ocs-24-starter-bundle/overview)
      ✔ supportsContract: Returns true for a supported contract (62ms)
      ✔ supportsContract: Returns false for an unsupported contract (95ms)
Error Simulating: undefined, {"calls":[{"type":"CALL","from":"0x965ef172b303b0bcdc38669df1de3c26bad2db8a","to":"0x7210587dd3df11efb7d6f34f970b32bf30bbc967","value":"0x2631116b55e000","gas":"0x80000000000000c0","gasUsed":"0x5518","input":"0x64869dad0000000000000000000000000cc9601298361e844451a7e35e1d7fcd72750e470000000000000000000000000000000000000000000000000000000000000001","error":"execution reverted"}],"logs":[]}
      1) createMintTemplateForUrl: Returns a mint template for a supported URL
      ✔ createMintForContract: Returns a mint template for a supported contract (406ms)
```

It looks like the `contractParams` on the MintInstructions will not correctly simulate. I haven't had a chance to look at why, but if you merge main into this repo, your tests should fail too and you can debug. 🙏

**Comment by mawutory** [comment]
thanks @chrismaddern for the review. 

i have merged main into this repo and the tests still do pass for me:

Screenshot from 2024-07-21 20-31-10

i assume that the address in `contractParams: '[address, 1]'` shall be replaced with the user (minter) address, no?

according to the ABI, that's the right input format and should work:

```
{
      "inputs": [
        {
          "internalType": "address",
          "name": "minter",
          "type": "address"
        },
        {
          "internalType": "uint256",
          "name": "quantity",
          "type": "uint256"
        }
      ],
      "name": "mintSeaDrop",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
```

**Comment by chrismaddern** [comment]
@mawutory you will need to add the value:

```
SIMULATE_DURING_TESTS=true
```

to your `.env` file — this will make it run an onchain simulation during tests.

This is in the .env.sample now, but you will have made your copy before that was added! 🙏

**Comment by mawutory** [comment]
@chrismaddern thanks!

please is there a way i could access the user address outside of the mint builder and maybe log it to the console?

**Comment by chrismaddern** [comment]
> @chrismaddern thanks!
> 
> 
> 
> please is there a way i could access the user address outside of the mint builder and maybe log it to the console?

Ofcourse.

The code that simulates it is also in this repo and you can see the address used here:

https://github.com/floornfts/mobile-minting/blob/main/src/lib/simulation/simulation.ts#L57

**Comment by mawutory** [comment]
@chrismaddern i know where the issue seems to be coming from. 

visibility of `mintSeaDrop()` on proxy contracts is marked as `nonpayable`, meaning that sending ether to the contract is handled differently.

i will push the edit in about ~2hrs

**Comment by mawutory** [comment]
@chrismaddern the simulation is successful only if the minter address is the same as the signer or an empty address 0x000... which reverts to the signer address as default. 

thus, we cannot mint to a user address. 

what happens now?

**Comment by chrismaddern** [comment]
Thanks @mawutory -- that is indeed a problem. That indicates that this minting method is not compatible with Mobile Minting (at least with the current integration approach)

I'm going to reach out to the Opensea team to see if there's a path forward here.

**Comment by mawutory** [comment]
@chrismaddern is there going to be a reward for the attempt? i am already working on a fix but that would require modifying `simulation.ts`. so i'm not really sure it's going to get merged.

**Comment by chrismaddern** [comment]
Closing this for now. Let's focus on getting your Manifold ingestor across the line.

We can revisit merging this (and will still pay the bounty if we do) if we can get Opensea onboard with giving our signers permission.

Will let you know!

**Pull request closed without merging**
