### PR TITLE
Ingestor OpenSea

### PR DESCRIPTION
**Pull request by pbkompasz**
OpenSea Ingestor
Closes: #7.
This uses the official OpenSea API, for which a key can be requested [here](https://docs.opensea.io/reference/api-keys).

### CODE REVIEW

**Comment by pbkompasz** [comment]
Output after running `yarn dry-run opensea url https://opensea.io/collection/parallel-ocs-24-starter-bundle/overview`
```
{
  "name": "Parallel OCS '24 Starter Bundle",
  "featuredImageUrl": "https://i.seadn.io/s/raw/files/cd729f7fce09a974c5dd2588f219393e.png?w=500&auto=format",
  "images": [
    {
      "url": "https://stream.mux.com/LIUBNjekxYo5g9CZfMO6FxzC7577WAPqrOaKgfGADl00/high.mp4",
      "caption": "banner"
    }
  ],
  "marketingUrl": "https://opensea.io/collection/parallel-ocs-24-starter-bundle/overview",
  "mintInstructionType": "EVM_MINT",
  "mintInstructions": {
    "chainId": 8453,
    "contractAddress": "0x00005EA00Ac477B1030CE78506496e8C2dE24bf5",
    "contractMethod": "mintPublic",
    "contractParams": "[\"0x7210587dd3df11efb7d6f34f970b32bf30bbc967\", \"0x0000a26b00c1f0df003000390027140000faa719\", \"0x0000000000000000000000000000000000000000\", address]",
    "abi": [
      {
        "inputs": [
          {
            "internalType": "address",
            "name": "nftContract",
            "type": "address"
          }
        ],
        "name": "getPublicDrop",
        "outputs": [
          {
            "components": [
              {
                "internalType": "uint80",
                "name": "mintPrice",
                "type": "uint80"
              },
              {
                "internalType": "uint48",
                "name": "startTime",
                "type": "uint48"
              },
              {
                "internalType": "uint48",
                "name": "endTime",
                "type": "uint48"
              },
              {
                "internalType": "uint16",
                "name": "maxTotalMintableByWallet",
                "type": "uint16"
              },
              {
                "internalType": "uint16",
                "name": "feeBps",
                "type": "uint16"
              },
              {
                "internalType": "bool",
                "name": "restrictFeeRecipients",
                "type": "bool"
              }
            ],
            "internalType": "struct PublicDrop",
            "name": "",
            "type": "tuple"
          }
        ],
        "stateMutability": "view",
        "type": "function"
      },
      {
        "inputs": [
          {
            "internalType": "address",
            "name": "nftContract",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "feeRecipient",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "minterIfNotPayer",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "quantity",
            "type": "uint256"
          }
        ],
        "name": "mintPublic",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function"
      }
    ],
    "priceWei": "10750000000000000"
  },
  "mintOutputContract": {
    "chainId": 8453,
    "address": "0x7210587dd3df11efb7d6f34f970b32bf30bbc967"
  },
  "liveDate": "2024-07-05T11:50:36.644Z",
  "availableForPurchaseStart": "2024-06-26T18:00:43.000Z",
  "availableForPurchaseEnd": "2024-09-04T18:00:43.000Z",
  "partnerName": "opensea",
  "promotionaltext": null,
  "creator": {
    "name": "ParallelContractDeployer",
    "walletAddress": "0x02f086dbc384d69b3041bc738f0a8af5e49da181",
    "websiteUrl": "https://parallel.life",
    "description": ""
  },
  "description": "Parallel Starter Bundle includes a Marcolian Assault Training Concept Art Cardback and a random Parallel Starter Pack of NFTs allowing you to play to win. As a bonus, receive five AP card packs when you download the game. \r\n\r\nParallel is a sci-fi based competitive card game where players build decks and face off, bank energy, and build armies to decide the fate of humanity.\r\n\r\nClaim your free card back and purchase a bundle to jump start your playing journey."
}

```

**Comment by chrismaddern** [comment]
Hi there 👋 

I haven't reviewed this one yet, since technically there is a submission for Opensea almost 1 week before this one.

I'm going to take a look at the Foundation one right now, and then will come back to this later. The first Opensea one has significant work to do, so the author may choose to push forward, or not.

**Comment by chrismaddern** [comment]
Hi @pbkompasz, given the quality of your other ingestor work, I decided to circle back round to this one.

I merged the latest state of main into it, and then added the basicIngestor tests to your Opensea tests:

```ts
  basicIngestorTests(new OpenSeaIngestor(), mintIngestorResources(), {
      successUrls: [
          'https://opensea.io/collection/parallel-ocs-24-starter-bundle/overview'
      ],
      failureUrls: [
          'https://www.example.com/',
          'https://opensea.io/'
      ],
      successContracts: [
          { chainId: 8453, contractAddress: '0x00005EA00Ac477B1030CE78506496e8C2dE24bf5' }
      ],
      failureContracts: [
          { chainId: 8453, contractAddress: '0x6140F00e4Ff3936702E68744f2b5978885464cbB' }
      ]
  }, {
      8453: '0xF469C6'
  });
```

This results in the following test output:

```bash
 opensea
    ✔ supportsUrl: Returns false for an unsupported URL
    ✔ supportsUrl: Returns true for a supported URL
    ✔ createMintTemplateForUrl: Returns a mint template for a supported URL (831ms)
    ✔ createMintTemplateForUrl: Throws error for non Base mint (300ms)
    ✔ createMintTemplateForUrl: Throws error if incompatible URL
    ✔ createMintTemplateForUrl: Throws error if non-existent project (97ms)
    ✔ createMintTemplateForContract: Returns a mint template for a supported contract (420ms)
    ✔ createMintTemplateForContract: Throws error for a non supported contract (80ms)
    ✔ supportsContract: Returns false for a non supported contract (62ms)
    ✔ supportsContract: Returns true for a supported contract (74ms)
    ✔ supportsContract: Returns false for a non supported chain
    OpenSeaIngestor-auto
      ✔ supportsUrl: Returns true for a supported URL
      ✔ supportsUrl: Returns false for unsupported url (https://www.example.com/)
      1) supportsUrl: Returns false for unsupported url (https://opensea.io/)
      2) supportsContract: Returns true for a supported contract
      ✔ supportsContract: Returns false for an unsupported contract (74ms)
Error Simulating: undefined, {"calls":[{"type":"CALL","from":"0x965ef172b303b0bcdc38669df1de3c26bad2db8a","to":"0x00005ea00ac477b1030ce78506496e8c2de24bf5","value":"0x2631116b55e000","gas":"0x80000000000000c0","gasUsed":"0x61e0","input":"0x161ac21f0000000000000000000000007210587dd3df11efb7d6f34f970b32bf30bbc9670000000000000000000000000000a26b00c1f0df003000390027140000faa71900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001","output":"0x13da22f2000000000000000000000000000000000000000000000000000000006673306f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","error":"execution reverted"}],"logs":[]}
      3) createMintTemplateForUrl: Returns a mint template for a supported URL
      4) createMintForContract: Returns a mint template for a supported contract


  14 passing (3s)
  4 failing

  1) opensea
       OpenSeaIngestor-auto
         supportsUrl: Returns false for unsupported url (https://opensea.io/):

      AssertionError: expected true to be false
      + expected - actual

      -true
      +false

      at Context.<anonymous> (test/shared/basic-ingestor-tests.ts:32:41)

  2) opensea
       OpenSeaIngestor-auto
         supportsContract: Returns true for a supported contract:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/shared/basic-ingestor-tests.ts:38:37)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  3) opensea
       OpenSeaIngestor-auto
         createMintTemplateForUrl: Returns a mint template for a supported URL:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/shared/basic-ingestor-tests.ts:58:49)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  4) opensea
       OpenSeaIngestor-auto
         createMintForContract: Returns a mint template for a supported contract:
     CouldNotResolveMint: Project not found
      at OpenSeaIngestor.createMintForContract (src/ingestors/opensea/index.ts:43:13)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Context.<anonymous> (test/shared/basic-ingestor-tests.ts:67:34)
```

I suspect there are a couple issues in the resolving contract → mint, but most notably it seems that the created mintinstructions do not simulate successfully.

(Digs in a little bit)

I noticed this comment:
`// The payer is always the mint recipient`

If this is true, then this minting form is not compatible with Mobile Minting :( 

Mobile Minting mints are _always_ signed by a signer wallet, and deposited into the user's wallet.

**Comment by pbkompasz** [comment]
@chrismaddern The tests and simulations all pass now. The issue was with the mint price and the added fee.

**Comment by chrismaddern** [comment]
@pbkompasz there was a pre-existing submission for opensea, https://github.com/floornfts/mobile-minting/pull/21 and this one is blocked by the fact that Opensea do not allow minting from one wallet, and delivering to another (a requirement for mobile minting)

Do you know how the tests pass if we can't do that?

**Comment by pbkompasz** [comment]
@chrismaddern `mintPublic` has a `minterIfNotPayer` field, which can be set to a zero address, and in that case the payer is the minter. I tried to leave it as `address` to send it to a test recipient, but then the execution reverts. Can't we just mint it and transfer it afterwards to the recipient?

This is the natspec:
```
/**
   * @notice Mint a public drop.
   *
   * @param nftContract      The nft contract to mint.
   * @param feeRecipient     The fee recipient.
   * @param minterIfNotPayer The mint recipient if different than the payer.
   * @param quantity         The number of tokens to mint.
*/
```

**Pull request closed without merging**
