### PR TITLE
feat-zora-base ingestor

### PR DESCRIPTION
**Pull request by Nith567**
### Functionality Supported
* Ingesting from URL: Yes
* Ingesting from Contract address: Yes
* Supported Networks: Base

### Before you submit
- [x] Ensure your generated MintTemplate works 😄
- [x] Ensure that your code is restricted to a single folder in `src/ingestors`
- [x] Ensure that all required assets are included (e.g. ABIs)
- [x] Ensure ABIs are trimmed to include only methods (1) used in the ingestor or (2) required to mint
- [x] Ensure that all exported methods are prefixed with the name of your ingestor e.g. `myMintingPlatformGetContractDetails`
- [x] Ensure that a test exists for generating a MintTemplate that will always succeed
- [x] Ensure that your code accesses **no external resources** except those passed in the `resources` object

### CODE REVIEW

**Comment by Nith567** [comment]
@chrismaddern  Can you pls give me an update ?

**Comment by chrismaddern** [comment]
Apologies @Nith567 I got pretty under water. Will do a full review of all outstanding PRs in the next day.

Unfortunately, many ingestors have had issues that have required 5+ rounds of feedback and has taken up more time than we really had to commit to this, but I will make sure to close these out.

**Comment by chrismaddern** [comment]
> unfortuantely rounds of feedback(long gap) took more than a month it could have done all in a week

Hi @Nith567 you are correct - you have submitted the largest number of unsuccessful, non-working PR submissions of any bounty submission. This PR seems to have been re-created from this earlier one.

https://github.com/floornfts/mobile-minting/pull/18

I have patiently allowed you to continue to attempt to get this working, and in the meantime, created a temporary one (even used the slug `zora-internal` to allow your work to target being the `zora` one).

I have continued to give feedback, and help coach on how to successfully write an ingestor, committed to helping you finish. Candidly, I did _not_ expect to receive attitude on the other side of that - I have spent more time trying to help you write this than it would have taken to write it myself.

At this point, let me know if you believe this is a _fully working_ submission and we'll give it one more review attempt before we entertain other submissions for this bounty.

**Comment by chrismaddern** [comment]
I just tried to take a look anyway, to see if I could get it across the line quickly, and it appears the automated tests are still failing:

CleanShot 2024-08-27 at 07 40 20@2x

@Nith567 can you add a Twitter or email to your Github profile so that I can message you 👀 🙏 😊

**Comment by Nith567** [comment]
Oh sorry for that i made few changes ( actually didnt check last time it was worked so didnt even think about a moment)
Now its working :)  My email ID  is : (nithinkatkam504106@gmail.com)

**Comment by chrismaddern** [comment]
Unfortunately this will not be merged. Thank you for the work here, and for your other contributions across mobile minting.

Closing this for now.

**Pull request closed without merging**
